# VersaLogic VersaAPI Sample Code Makefile - 20160225
#
# This code is given with no guarantees and is intended to be used as an 
# example of how to use the VersaAPI software package and to check the 
# operation post install. 
#
# Usage: 	make clean	=> Removes all dependant .o files.
#		make 		=> Builds pushButton application.
#
# Build fruit is an example application 'pushButton'

# ********** Library section *********
LIBS=	/usr/local/lib/libVL_OSALib.so
CG_LIBS=/usr/local/lib/libVL_OSALib.so /usr/local/lib/libcgos.so

# ************************************

INCLUDEPATHS=	-I. -I/usr/include

O_FILES=	pushButton.o
SRC_FILES=	pushButton.c

all:	example

example:	$(O_FILES)
	@echo 'Building target: $@'
	gcc -o pushButton $(DIO_FLAG) $(O_FILES) $(INCLUDEPATHS) $(LIBS)
	@echo 'Finished building target: $@'
	@echo ' '

example_cg:	$(O_FILES)
	@echo 'Building target: $@'
	gcc -o pushButton $(DIO_FLAG) $(O_FILES) $(INCLUDEPATHS) $(CG_LIBS)
	@echo 'Finished building target: $@'
	@echo ' '

clean:	
	rm *.o pushButton

%.o: %.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -Wall -c $(DIO_FLAG) $(INCLUDEPATHS) -fmessage-length=0 -o "$@" "$<"
	@echo 'Finished building: $<'


