network:
  ethernets:
    eth0:
      dhcp4: true
      # addresses: [192.168.5.31/24]
      optional: true
      match: 
        macaddress: 00:18:7d:3a:97:25
      set-name: eth0
    eth1:
      dhcp4: false
      dhcp6: false
      addresses: 
        - 192.168.1.31/16
        - 192.168.0.31/24
        - 192.168.113.101/24
      gateway4: 192.168.1.254
      nameservers:
        addresses: [192.168.1.254]
      optional: true
      match:
        macaddress: 00:18:7d:3a:97:26
      set-name: eth1
  version: 2
  renderer: networkd
