# This is the network config written by 'subiquity'
network:
  ethernets:
    eth0:
      dhcp4: true
      optional: true
    eth1:
      dhcp4: true
      optional: true
  version: 2
  renderer: networkd
