modem/modem_config:
    # tcp_config/ip: 192.168.0.150 # real IP
    tcp_config/ip: 10.42.10.10 # simulation IP
    # local_address: 150 # real address
    local_address: 10 # simulation address
    hasAHRS: false
    initializer: "{'@ZA': '1', '@ZX': '1'}"

pinger:
    tslack: 1.0
    # modem_name: "192.168.0.150" # real IP
    modem_name: "10.42.10.10" # simulation IP
    #modems_list: ["1", "2"]
    modems_list: ["8", "8"]
    timeout_list: [4.0, 4.0]

replier:
    tslack: 1.0
    # modem_id: 150 # real
    modem_id: 10 # sim
    timeout_list: [4.0, 4.0]

data_serializer:
    # vehicle_id: 150 # real
    vehicle_id: 10 # sim

pos2sim_modem:
    # ip: 192.168.0.150 # real IP
    ip: 10.42.10.10 # simulation IP

dmac2farol:
    # false, vehicle acts as an achor, estimates other vehicles position 
    # true, vehicle estimates its own position with respect to an anchor   
    fix_type: true
    # true, real vehcile
    # false, simulation scenarios with evo emulator
    real: true
    installation_matrix: [-0.7854, 0, 3.1415]