#############
# Altimeter #
#############
altimeter:
    type: micron
    port: /dev/medusa/altimeter
    baudrate: 9600
    frame_id: altimeter

#############
# Bluetooth #
#############
bluetooth:
    port: /dev/medusa/bluetooth
    baudrate: 115200

##############
# Nortek DVL #
##############
nortek_dvl:
    nucleus1000_driver:
        ip: 192.168.0.201
    dvl2farol:
        dvl_to_filter: True
        ahrs_to_filter: False
        altimeter_to_filter: False

###########
# A50 DVL #
###########
a50_dvl:
    ip: 192.168.0.95

#######
# BMS #
#######
bat_monit:
    serial_port: "/dev/medusa/batmonit"
    baudrate: 57600
    battery:
        packs: 2
        cells: 7
        err_voltage: 3400
        warn_voltage: 3500

##############
# Depth Cell #
##############
depth_cell:
    port: /dev/medusa/depth_cell
    baudrate: 57600
    frame_id: depth

#######
# GPS #
#######
gps:
    port: /dev/medusa/gps
    baudrate: 115200
    rtk_port: 24387
    frame_id: gnss
    config_commands: [
    # RTK rover configuration. 
    "PASHS,CPD,FST,ON",        # Fast RTK  -->
    "PASHS,CPD,BAS,0",         # Static base  -->
    "PASHS,CPD,AFP,99",        # Confidence level (fixed RTK) [default 99%]  -->
    "PASHS,CPD,RST",           # RTK Process Reset  -->
    # Data for online processing.  -->
    "PASHS,NME,POS,A,ON,0.2",  # PASHR,POS at 5Hz  -->
    "PASHS,NME,ZDA,A,ON,1",    # GPZDA time and date once per second -->
    "PASHS,NME,GGA,A,ON,1",    # GPGGA once per second -->
    "PASHS,NME,SAT,A,ON,1",    # PASHR,SAT at 1Hz  -->
    # Data for offline processing.  -->
    # "PASHS,RAW,SNV,A,ON,0.5", -->  # Raw ephemeris at 2Hz  -->
    # "PASHS,RAW,PBN,A,ON,0.5", -->   # Raw position at 2Hz  -->
    # "PASHS,RAW,MCA,A,ON,0.5", -->   # Raw measurements at 2Hz  -->
    "PASHS,RAW,ALL,A,OFF",          # All Raw messages off on port A  -->
    # Other -->
    "PASHS,PEM,5",             # Position elevation mask [default 5deg] -->
    "PASHS,DYN,4",             # Dynamic mode: ship  -->
    "PASHS,SMI,100,600,1800",  # [MB100] Smoothing [default 100, 600, 1800]-->
    "PASHS,ANT,EXT",           # Set the antenna -->
    "PASHS,PPS,1,0,R",         # PPS message at 1Hz -->
    "PASHS,SOM,SNR,10",        # Signal-to-Noise Ratio Mask [default 28] -->
    ]     

#######
# IMU #
#######
imu:
    port: /dev/medusa/imu
    baudrate: 115200
    use_position: false
    frame_id: ahrs
    config_commands: [
        "VNWRG,06,0", # Stop Asynch 
        "VNRFS", #  Restore factory resets
        "VNWRG,25,1,0,0,0,1,0,0,0,1,-0.3450,0.0,-1.533", # accel calibration (bias calculated by hand)
        "VNWRG,84,1,0,0,0,1,0,0,0,1,-0.001872,0.016847,0.000502", # gyro calibration (bias calculator)  
        "VNWRG,06,0", #  Stop Asynch (default msg is YMR reg6_14, 40 Hz)  
        "VNWRG,35,0,0,0,0", #  VPE Disabled  
        "VNWRG,36,5,5,5,0,0,0,0,0,0", #  trust (5) in mags and no adaptive tuning or filtering (IF VPE Off, is irrelevant.)  
        "VNWRG,44,0,1,5", #  Turn OFF real-time mag calibration algorithm and output compensation)  
        "VNWRG,26,0,0,-1,1,0,0,0,-1,0", #  Reference Frame (Sensor to Body)  
        #"VNWRG,83,1,1,0,0,1000,2016.1,+43.933115,+15.444187,+100.000", #  Use Mag and Grav Models for Lisbon  
        # "VNWRG,23,1,0,0,0,1,0,0,0,1,0,0,0",   #  Identity  
        # "VNWRG,23,0.9163,-0.0009,0,-0.0009,1.0913,0,0,0,1,0.0128,0.0212,0",  
         
         "VNWRG,23,1.0939,-0.0000,0.0042,-0.0000,1.000,0,0.0042,0.0000,0.9142,0.0197,0.000,-0.0142",   #  Calibration made on 20210702  
         #  Calibration made on 20210702  
        #  "VNWRG,23,1,0,0,0,1,0,0,0,1,0.0051,-0.0500,-0.0104",   #  Calibration made on 20150510  
        #  "VNWRG,23,1,0,0,0,1,0,0,0,1,0.0053,-0.0967,-0.0044",   #  Calibration made on 20150511  
        #"VNWRG,23,1,0,0,0,1,0,0,0,1,-0.0114,-0.4490,-0.0007", #  Calibration made on 20161118 HF and MF modem  
        # VNWRG,23,1.0728,0.0192,0.0136,0.0192,0.9806,-0.0175,0.0136,-0.0175,-0.8348,-0.0186,-0.0383, 0,0205", #  Calibration made on 20161118 HF and MF modem  
        "VNWNV", #  Write settings to  memory  
        "VNRST", #  Reset the Kalman Filter  
        ]
    check_commands: [
        "VNWRG,07,10", #  Asynch data output rate 10 Hz  
        "VNWRG,06,14", #  (reg6_14) YMR, Magnet, Accel m/s^2, Gyros rad/s  
        #"VNRRG,21", #  Read Mag and Grav model vectors  
        "VNRRG,23", #  Read Calibration mode  
        "VNRRG,26", #  Install matrix  
        "VNRRG,35", #  VPE Basic Control  
        "VNRRG,36", #  Basic Magnetometers Configuration  
        "VNRRG,37", #  Advanced Magnetometers Configuration  
        #"VNRRG,83", #  Read Mag and Grav model cfg and position/date  
        ]


###################
# Inside Pressure #
###################
inside_pressure:
    port: /dev/medusa/inside_pressure
    baudrate: 19200
    max_inside_pressure: 650.0 # bar
    min_inside_pressure: 200.0 #bar
    max_inside_temperature: 50 # Celsius
    min_inside_temperature: 0 # Celsius


#########
# Leaks #
#########
leaks:
    names: ["upper","lower"]
    address: [16,32]

################
# Magnetometer #
################
magnetometer:
    PORT: /dev/medusa/payload
    BAUDRATE: 9600
    vehicle_name: "mvector"
    node_frequency: 1.0 

#############
# Thrusters #
#############

thrusters_0_1:
    thrust_id: [0,1]
    thrust_offset: [0,3]
    num_thrusters: 6
    test_duration: 3
    usb:
        vid: "0xF4D8"
        pid: "0x0001"
        sn: "TD000"
        bcd: "0x0208"
    
    
thrusters_2_3:
    thrust_id: [2,3]
    thrust_offset: [6,9]
    num_thrusters: 6
    test_duration: 3
    usb:
        vid: "0xF4D8"
        pid: "0x0001"
        sn: "TD002"
        bcd: "0x0208"

thrusters_4_5:
    thrust_id: [4,5]
    thrust_offset: [12,15]
    num_thrusters: 6
    test_duration: 3
    usb:
        vid: "0xF4D8"
        pid: "0x0001"
        sn: "TD006"
        bcd: "0x0208"

#################
# Optical modem #
#################
optical_modem:
    node_frequency: 2.0
    port: "/dev/medusa/optical_modem"
    baud: 115200
