watchdog:
    node_frequency: 10.0
    shore_frequency: 1.0
    acoustic_frequency: 0.05
    safety_frequency: 2.0
    depth_transition: 0.3 #meters - value from which to assume that the vehicle is submerged
    shore_vehicle_id: 1 
    relay_vehicle: false

aggregator:
    pub_rate: 2.0
    analyzers:
        sensors:
            type: diagnostic_aggregator/StatusAnalyzer
            path: Sensors
            analyzers:
                leaks:    
                    type: diagnostic_aggregator/GenericAnalyzer
                    path: Leaks
                    contains: Leaks
                pressure:
                    type: diagnostic_aggregator/GenericAnalyzer
                    path: Pressure
                    contains: Pressure
                temp:
                    type: diagnostic_aggregator/GenericAnalyzer
                    path: Temperature
                    contains: Temperature
                imu:
                    type: diagnostic_aggregator/GenericAnalyzer
                    path: IMU
                    contains: IMU
                gps:
                    type: diagnostic_aggregator/GenericAnalyzer
                    path: GPS
                    contains: GPS
                altimeter:
                    type: diagnostic_aggregator/GenericAnalyzer
                    path: Altimeter
                    contains: Altimeter
                depth_cell:
                    type: diagnostic_aggregator/GenericAnalyzer
                    path: DepthCell
                    contains: DepthCell
        actuators:
            type: diagnostic_aggregator/StatusAnalyzer
            path: Actuators
            analyzers:
                thruster_0:
                    type: diagnostic_aggregator/GenericAnalyzer
                    path: Thruster0
                    contains: Thruster0
                thruster_1:
                    type: diagnostic_aggregator/GenericAnalyzer
                    path: Thruster1
                    contains: Thruster1
                thruster_3:
                    type: diagnostic_aggregator/GenericAnalyzer
                    path: Thruster3
                    contains: Thruster3
                thruster_2:
                    type: diagnostic_aggregator/GenericAnalyzer
                    path: Thruster2
                    contains: Thruster2
                thruster_4:
                    type: diagnostic_aggregator/GenericAnalyzer
                    path: Thruster4
                    contains: Thruster4
                thruster_5:
                    type: diagnostic_aggregator/GenericAnalyzer
                    path: Thruster5
                    contains: Thruster5
        power_system:
            type: diagnostic_aggregator/StatusAnalyzer
            path: Power System
            analyzers:
                batmonit:
                    type: diagnostic_aggregator/GenericAnalyzer
                    path: Batmonit
                    contains: Batmonit
