high_voltage: 1500
save_folder: "/home/ubuntu/gsniffer_saves"
sample_period: 10.0
acquisition_mode: "none"
# acquisition_time: 100
stop_acquisition_before_sampling: false
channels: 4096
lld: 0
uld: 4095
first_channel: 0
last_channel: -1

# Calibration
calibration_slope: 1.0
calibration_offset: 0.0
calibration_square: 0.0