## --------------------------- ## 
#   Overide configurations      #
## --------------------------- ##


## --------------------------- ## 
#   Network Ports              #
## --------------------------- ##
addons/console_server:
    PORT: 7080

cooperative/cpf_wifi_server:
    broadcast_port: 2808

cooperative/cpf_wifi_client:
    broadcast_port: 2808


## --------------------------- ## 
#   Additional configurations   #
## --------------------------- ##

## --------------------------- ## 
#   glider_addons               #
## --------------------------- ## 
glider_addons:

    watchdog:
        topics:
          subscribers:
              state: /#vehicle#/nav/filter/state
              usbl_fix: /#vehicle#/sensors/usbl_fix
              shore_vehicle: /#vehicle#/watchdog/shore_vehicle
              acoustic_safety_abort: /#vehicle#/acomms/safety_abort
              wifi_client: /#vehicle#/watchdog/client
          publishers:
              thruster_stop: /#vehicle#/Thruster_Stop
              flag: /#vehicle#/Flag
              safety_feature: /#vehicle#/Safety_Feature
              safety_abort: /#vehicle#/watchdog/safety_abort
        services:
          force_wifi: /#vehicle#/watchdog/force_wifi

## --------------------------- ## 
#   glider_drivers              #
## --------------------------- ## 
drivers:
  leaks:
      node_frequency: 2.0
      topics:
          subscribers:
              data: /#vehicle#/drivers/parallel_port/data
          publishers:
              thruster_stop: /#vehicle#/Thruster_Stop
              diagnostics: /#vehicle#/diagnostics

  parallel_port:
        node_frequency: 1.0
        topics:
            subscribers: 
                conf: /#vehicle#/drivers/parallel_port/conf
            publishers:
                data: /#vehicle#/drivers/parall

## --------------------------- ## 
#   glider_bsd_interface        #
## --------------------------- ## 

GliderBsdInterfaceNode:
    vehicle_name: "#vehicle#"
    topics:
        subscribers:
            m_gps_lat: "/glider0/glider/extctl/sensors/m_gps_lat"
            m_gps_lon: "/glider0/glider/extctl/sensors/m_gps_lon"
            m_depth: "/glider0/glider/extctl/sensors/m_depth"
            m_pitch: "/glider0/glider/extctl/sensors/m_pitch"
            yaw_ref: "/#vehicle#/ref/yaw"
            surge_ref: "/#vehicle#/ref/surge"
        publishers:
            position: "/#vehicle#/measurement/position"
            # c_depth: